[versions]
kotlin = "2.1.0"
compose = "1.7.0"
agp = "8.13.2"
ktor = "3.0.0"
coroutines = "1.9.0"
serialization = "1.7.3"
jsoup = "1.18.1"
logback = "3.0.0"
vlcj = "4.8.3"
logback-classic = "1.5.6"
room = "2.7.0-alpha11"
ksp = "2.1.0-1.0.29"
sqlite = "2.5.0-alpha11"
[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version = "4.13.2" }

# Android
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.2" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.7.7" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version = "1.3.0" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version = "1.3.0" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version = "1.3.0" }
coil-compose = { module = "io.coil-kt:coil-compose", version = "2.6.0" }


# Compose
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "compose" }
compose-webview = { module = "io.github.kevinnzou:compose-webview-multiplatform", version = "1.9.40-alpha04" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }

# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Jsoup
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

# Logging
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version = "7.0.0" }
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.5.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
